config/routes.rb
Lookshelf::Application.routes.draw do

  resources :tags do
    collection do
      post "request_book"
    end
  end

  match "account_settings" => "users#account_settings"
  match "zoom_in/:id" => "shelf#zoom_in", :as => "zoom_in"
  match "load_tags" => "tags#load_tags"
  match "save_tag" => "tags#save_tag"
  match "delete_tag" => "tags#delete_tag"
  match "borrower_page" => "shelf#borrower_page"
  match "lender_page" => "shelf#lender_page"
  match "accept_request/:id" => "shelf#accept"
  match "reject_request/:id" => "shelf#reject"
  match "loaned_out/:id" => "shelf#loaned_out"

  root :to => "users#home"
  resources :users

end

app/controllers/shelf_controller.rb
class ShelfController < ApplicationController
   before_filter :is_user_allowed
   before_filter :is_registered, :only => [:zoom_in]
  
  
  def zoom_in

    @user = User.find(params[:id])
  end

  def borrower_page
#    @waiting_list = Lender.find(:all, :conditions => ["borrower_id = ? AND status = ?", self.current_user.id, Lender::WAITING])
#    @received_list = Lender.find(:all, :conditions => ["borrower_id = ? AND status = ?", self.current_user.id, Lender::RECEIVED])
#    @loaned_out_list = Lender.find(:all, :conditions => ["borrower_id = ? AND status = ?", self.current_user.id, Lender::LOANED_OUT])
   @waiting_list = Lender.where(["borrower_id = ? AND status = ?", self.current_user.id, Lender::WAITING])
   logger.info(@waiting_list.size)
    @received_list = Lender.where(["borrower_id = ? AND status = ?", self.current_user.id, Lender::RECEIVED])
    logger.info(@received_list.size)
    @loaned_out_list = Lender.where(["borrower_id = ? AND status = ?", self.current_user.id, Lender::LOANED_OUT])
    logger.info(@loaned_out_list.size)


  end

  def lender_page

    @request_list = Lender.where(["lender_id = ? AND status = ?", self.current_user.id, Lender::WAITING])

    @sent_list = Lender.where(["lender_id = ? AND status = ?", self.current_user.id, Lender::RECEIVED])
    @over_due_list  = Lender.where(["lender_id = ? AND status = ?", self.current_user.id, Lender::OVER_DUE])
    
  end

  def accept
    @lender = Lender.find(params[:id])
    @lender.update_attribute(:status, Lender::RECEIVED)
    redirect_to :action => "lender_page"
  end


  def reject

    @lender = Lender.find(params[:id])
    @lender.update_attribute(:status, Lender::LOANED_OUT)
    redirect_to :action => "lender_page"
  end

  def loaned_out

    @lender = Lender.find(params[:id])
    @lender.update_attribute(:status, Lender::LOANED_OUT)
    redirect_to :action => "lender_page"
  end
end

app/helpers/shelf_helper.rb
module ShelfHelper
end

app/views/shelf/borrower_page.html.erb
<div class="contentbottom">
  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  
  <h2 style="float:left;margin-left:90px;">Here are the books you would like to borrow</h2>

  <%@waiting_list.each do |list|%>   
   <h3 style="float:left;margin-left:90px;"><%=list.lender_name%> has not responded yet.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greybox">
    <div class="greybox_con">
      <div class="headingcontent">Book Title:</div><div class="datacontent">test<%=list.book_title%></div>
      <div class="headingcontent">Date of request:</div><div class="datacontent"><%=list.date_of_request%></div>
      <div class="headingcontent">Estimated delivery:</div><div class="datacontent"><%=list.estimated_delivery_date%></div>
      <!--<span class="fontitalic"> Lorem ipsum dolor sit amet, </span> </div>-->
    <button id="submitButton" class="greyButton" onclick="return false;" type="submit">Waiting...</button>
  </div>
  </div>
    <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  <%end%>


 <%@received_list.each do |list|%>
     <h3 style="float:left;margin-left:90px;color:#01DF3A;"><%=list.lender_name%> is willing to loan you this book.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greenbox">
    <div class="greenbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="greenButton" onclick="return false;" type="submit">Received</button>
  </div>
  </div>
    <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
 <%end%>


 <%@loaned_out_list.each do |list|%>
     <h3 style="float:left;margin-left:90px;color:#FD030C;"><%=list.lender_name%> is not willing to loan you this book.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
      <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="redbox">
    <div class="redbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="redButton" onclick="return false;" type="submit">Loaned out</button>
  </div>
  </div>
       <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
 <%end%>




 <!-- <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  
 <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greenbox">
    <div class="greenbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="greenButton" onclick="return false;" type="submit">Received</button>
  </div>
  </div>
 

  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>

 
    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="redbox">
    <div class="redbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="redButton" onclick="return false;" type="submit">Loaned out</button>
  </div>
  </div>-->
  <!--<div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  <div class="bluebox">
    <div class="bluebox_con">
      <div class="headingcontent">Special Number Three:</div>
      <span class="fontitalic"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis faucibus libero.bibendum interdum, nisl arcu pellen </span> </div>
    <button id="submitButton" class="blueButton" onclick="return false;" type="submit">Waiting</button>
  </div>-->
  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div></div>
  <div>
  <h3 style="float:left;margin-left:340px;"> What else are you interested in? </h3>
  <button style="margin-top:10px;margin-right:175px;" class="greyButton" onclick="window.location = '<%=root_url%>'" type="submit">Keep looking</button>
  
  
</div>


   <!-- <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <div class="blueboxafter"><img src="images/spacer.gif" alt="" border="0" /></div>-->

 

app/views/shelf/lender_page.html.erb
<div class="contentbottom">
  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>

  <h2 style="float:left;margin-left:90px;">Here are your books members would like to borrow</h2>

  <%@request_list.each do |list|%>
   <h3 style="float:left;margin-left:90px;"><%=list.borrower_name%> would like to borrow a book.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greybox">
    <div class="greybox_con">
      <div class="headingcontent">Book Title:</div><div class="datacontent">test<%=list.book_title%></div>
      <div class="headingcontent">Date of request:</div><div class="datacontent"><%=list.date_of_request%></div>
      <div class="headingcontent">Return date:</div><div class="datacontent">Coming soon..</div>
      <!--<span class="fontitalic"> Lorem ipsum dolor sit amet, </span> </div>-->
    <button id="submitButton" class="greenButton" onclick="window.location = '/accept_request/<%=list.id%>'" type="submit">Yes</button>
    <button id="submitButton" class="redButton" onclick="window.location = '/reject_request/<%=list.id%>'" type="submit">No</button>
    <button id="submitButton" class="orangeButton" onclick="window.location = '/loaned_out/<%=list.id%>'" type="submit">Loaned Out Already</button>
  </div>
  </div>
    <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  <%end%>


 <%@sent_list.each do |list|%>
     <h3 style="float:left;margin-left:90px;color:#01DF3A;"><%=list.borrower_name%> still has your book.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greenbox">
    <div class="greenbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="greenButton" onclick="return false;" type="submit">Received</button>
  </div>
  </div>
    <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
 <%end%>


 <%@over_due_list.each do |list|%>
     <h3 style="float:left;margin-left:90px;color:#FD030C;"><%=list.borrower_name%> still has your book.</h3>
   <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
      <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="redbox">
    <div class="redbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="orangeButton" onclick="return false;" type="submit">Overdue book</button>
  </div>
  </div>
       <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
 <%end%>




 <!-- <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>

 <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="greenbox">
    <div class="greenbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="greenButton" onclick="return false;" type="submit">Received</button>
  </div>
  </div>


  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>


    <img src="images/85x63.gif" alt="" class="borrowerImage" />
  <div class="redbox">
    <div class="redbox_con">
      <div class="headingcontent">Book Title:</div>
      <div class="headingcontent">Date of request:</div>
      <div class="headingcontent">Return date:</div>
    <button id="submitButton" class="redButton" onclick="return false;" type="submit">Loaned out</button>
  </div>
  </div>-->
  <!--<div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
  <div class="bluebox">
    <div class="bluebox_con">
      <div class="headingcontent">Special Number Three:</div>
      <span class="fontitalic"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis faucibus libero.bibendum interdum, nisl arcu pellen </span> </div>
    <button id="submitButton" class="blueButton" onclick="return false;" type="submit">Waiting</button>
  </div>-->
  <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
</div>
   <!-- <div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>
    <div class="blueboxafter"><img src="images/spacer.gif" alt="" border="0" /></div>-->

 

app/views/shelf/zoom_in.html.erb
<style type="text/css">

  div.photo-container {
    float: left ;
    margin-right: 10px ;
  }

</style>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
<%= javascript_include_tag "phototagger.jquery" %>
<script type="text/javascript">

  // When the DOM is ready, initialize the scripts.
  jQuery(function( $ ){

    // Set up the photo tagger.
    $( "div.photo-container" ).photoTagger({

      // The API urls.
      loadURL: "../load_tags",
      saveURL: "../save_tag",
      deleteURL: "../delete_tag",

      // Default to turned on.
      // isTagCreationEnabled: false,

      // This will allow us to clean the response from
      // a ColdFusion server (it will convert the
      // uppercase keys to lowercase keys expected by
      // the photoTagger plugin.
      cleanAJAXResponse: function( apiAction, response ){
        // Check to see if this it the load.
        if (apiAction == "load"){

          // Loop over response array.
          $.each(
          response,
          function( index, tagData ){
            // Translate the ColdFusion keys
            // to lowercase. This will create
            // dupliate keys, but it doesn't
            // matter for our use-case.
            $.each(
            tagData,
            function( key, value ){
              tagData[ key.toLowerCase() ] = value;
            }
          );

          }
        );

        }

        // Return cleaned response.
        return( response );
      }
    });
				
		


    // Hook up the enable create links.
    $( "a.enable-create" ).click(
    function( event ){
      // Prevent relocation.
      event.preventDefault();

      // Get the container and enable the tag
      // creation on it.
      $( this ).prevAll( "div.photo-container" )
      .photoTagger( "enableTagCreation" )
      ;
    }
  );


    // Hook up the disabled create links.
    $( "a.disable-create" ).click(
    function( event ){
      // Prevent relocation.
      event.preventDefault();

      // Get the container and enable the tag
      // creation on it.
      $( this ).prevAll( "div.photo-container" )
      .photoTagger( "disableTagCreation" )
      ;
    }
  );


    // Hook up the enable delete links.
    $( "a.enable-delete" ).click(
    function( event ){
      // Prevent relocation.
      event.preventDefault();

      // Get the container and enable the tag
      // deletion on it.
      $( this ).prevAll( "div.photo-container" )
      .photoTagger( "enableTagDeletion" )
      ;
    }
  );


    // Hook up the disabled delete links.
    $( "a.disable-delete" ).click(
    function( event ){
      // Prevent relocation.
      event.preventDefault();

      // Get the container and disabled the tag
      // deletion on it.
      $( this ).prevAll( "div.photo-container" )
      .photoTagger( "disableTagDeletion" )
      ;
    }
  );

  });

</script>
<h1>
  Shelf zoom view with tagging
</h1>


<div class="photo-column" style="float:left;">

  <div class="photo-container">
    <!--<img
      id="<%#=@user.id%>"
      src="/system/shelf_images/2/small/MC 85312251 1.jpg?1308063155"
      width="520"
      height="347"
      alt="Sexy woman used for demo."
      />-->
    <% if @user.shelf_image.exists? then %>
      <%= image_tag @user.shelf_image.url(:small), :id => @user.id %>


    <%else%>
      <img src="images/200x150.gif" alt="" style="" />
    <% end %>


  </div>

  <!-- These will toggle the tag ceation. -->
  <a href="#" class="enable-create">Enable Tagging</a>
  &nbsp;|&nbsp;
  <a href="#" class="disable-create">Disable Tagging</a>

  <br />
  <br />

  <!-- These will toggle the tag deletiong. -->

  <a href="#" class="enable-delete">Enable Tagging</a>
  &nbsp;|&nbsp;
  <a href="#" class="disable-delete">Disable Tagging</a>

</div>
<div class="contentsep"><img src="images/spacer.gif" alt="" border="0" /></div>

<div style="float:left;">
  <%= form_for :search, :url => request_book_tags_url, :html => {:style => "float:left"} do |f| %>
    <br/>
    <input type="text" name="tag" value="" />
    <%=f.hidden_field :user_id, :value => @user.id%>
    <!--<input type="image" src="../images/Search-icon2.png" class="searchbox_submit" value="" />-->
    <%= f.submit "Request Book" %>
  <%end%>
</div>










<!--

<h1>Shelf zoom view with tagging</h1>
<div class="spacerdiv"> </div>
<div class="left"><img src="images/spacer.gif" alt="" border="0" /></div>


<div class="box">
<%# if @user.shelf_image.exists? then %>
    <div style="width: 500px; height:400px;"><%#= image_tag @user.shelf_image.url(:small) %></div>


<%#else%>
    <div id="topstory-img"><img src="images/200x150.gif" alt="" style="" /></div>
<%# end %>

</div>--> <!-- /box -->