config/routes.rb
Lookshelf::Application.routes.draw do

  resources :tags do
    collection do
      post "request_book"
    end
  end

  match "account_settings" => "users#account_settings"
  match "zoom_in/:id" => "shelf#zoom_in", :as => "zoom_in"
  match "load_tags" => "tags#load_tags"
  match "save_tag" => "tags#save_tag"
  match "delete_tag" => "tags#delete_tag"
  match "borrower_page" => "shelf#borrower_page"
  match "lender_page" => "shelf#lender_page"
  match "accept_request/:id" => "shelf#accept"
  match "reject_request/:id" => "shelf#reject"
  match "loaned_out/:id" => "shelf#loaned_out"

  root :to => "users#home"
  resources :users

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :tag
  belongs_to :shelf, :conditions => "shelf_name != null", :foreign_key => :user_id
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :is_user_allowed
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  def search
    
  end

  def request_book
    logger.info(self.current_user.id)
    @book = Tag.find(:first, :conditions => ["title = ? AND user_id = ?",params[:tag], params[:search][:user_id]])
    #already requested then dont create the record again.
    @lender = Lender.find(:first, :conditions => ["borrower_id = ? AND lender_id = ? AND status = ? AND tag_id = ?",self.current_user.id, params[:search][:user_id],Lender::WAITING, @book.id ]) || Lender.new(:lender_id => @book.user_id, :borrower_id => self.current_user.id, :date_of_request => Date.today, :status => Lender::WAITING, :tag_id => @book.id)
    logger.info(@lender.new_record?)
    @lender.save
    redirect_to :controller => "shelf", :action => "borrower_page"
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end

  def load_tags
    @tags = Tag.find(:all, :conditions => ["user_id = ?", params[:photoID]])
    data = []
    @tags.each do |tag|
      data << {"id" => tag.id, "PHOTOID" => tag.user_id, "X" => tag.x, "Y" => tag.y, "WIDTH" => tag.width, "HEIGHT" => tag.height, "MESSAGE" => tag.title}
    end
    # data = '[{"ID": "91BEE419-FFAE-1669-D1C2D19C8AC13C9A", "PHOTOID":"1","Y":148,"WIDTH":127,"HEIGHT":84,"MESSAGE":"amazing","X":237}]'
    # render :json => '[{"ID": "91BEE419-FFAE-1669-D1C2D19C8AC13C9A", "PHOTOID":"1","Y":148,"WIDTH":127,"HEIGHT":84,"MESSAGE":"amazing","X":237}]'
    render :json => data
    #render :json => '[]'
  end

  def save_tag

    @tag = Tag.new(:x => params[:x], :y => params[:y], :width => params[:width], :height => params[:height], :title => params[:message], :user_id => params[:photoID])
    @tag.save
    render :json => '[]'
  end

  def delete_tag
    render :json => '[]'
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Author</th>
    <th>Title</th>
    <th>Topic</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.subject %></td>
    <td><%= tag.author %></td>
    <td><%= tag.title %></td>
    <td><%= tag.topic %></td>
    <td><%= tag.user_id %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @tag.subject %>
</p>

<p>
  <b>Author:</b>
  <%= @tag.author %>
</p>

<p>
  <b>Title:</b>
  <%= @tag.title %>
</p>

<p>
  <b>Topic:</b>
  <%= @tag.topic %>
</p>

<p>
  <b>User:</b>
  <%= @tag.user_id %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>