config/routes.rb
Lookshelf::Application.routes.draw do

  resources :tags do
    collection do
      post "request_book"
    end
  end

  match "account_settings" => "users#account_settings"
  match "zoom_in/:id" => "shelf#zoom_in", :as => "zoom_in"
  match "load_tags" => "tags#load_tags"
  match "save_tag" => "tags#save_tag"
  match "delete_tag" => "tags#delete_tag"
  match "borrower_page" => "shelf#borrower_page"
  match "lender_page" => "shelf#lender_page"
  match "accept_request/:id" => "shelf#accept"
  match "reject_request/:id" => "shelf#reject"
  match "loaned_out/:id" => "shelf#loaned_out"

  root :to => "users#home"
  resources :users

end

app/views/layouts/_flash.erb
<%
{
  :error=>{:color=>'red', :default=>'FAIL!'},
  :notice=>{:color=>'green', :default=>'SUCCESS!'}
}.each do |k, v|
%>
  <% if flash and flash[k] %>
    <div style="color:<%=v[:color]%>">
      <% flash[k] == :default ? v[:default] : flash[k] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_user.erb
<div class="loginBox">
  <% if current_user %>
  <div style="float:left;">Hello <%= link_to current_user, "../account_settings" %>, </div><div style="float:right;margin-left:7px;"> <%= button_to 'Sign out', current_user, :method=>:delete, :class => 'greyShadebutton' %></div>
  <% else %>
    Hi Lookshelf user, please <%#= link_to 'login!', new_user_path %> <%=raw RPXNow.popup_code('Sign in','lookshelf', users_url, :class => 'greyShadebutton') %>
    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Lookshelf</title>

    <meta name="description" content="Lookshelf" />
    <meta name="keywords" content="Lookshelf" />
<%#= stylesheet_link_tag :all %>
<%#= stylesheet_link_tag 'reset', 'base' %>
    <%= stylesheet_link_tag 'style' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>


  <body >    

    <div id="wrapper" style="margin-top: 10px;">
      <div class="topspacer"><img src="images/spacer.gif" alt="" border="0" /></div>
      <div class="mainblackborder">

        <!-- /middlecontent -->

        <!-- middlecontent -->
        <div class="middlecontent">
          <div><%= render 'layouts/user' %></div>
          <%= render 'layouts/flash', :locals => { :flash => flash } %>
          <%= yield %>
        </div>
        <!-- /middlecontent -->
        <!-- /middlecontent -->
        <!-- footer -->
        <div class="footer">
          <div class="footerbeforebg"><img src="images/spacer.gif" alt="" border="0" /></div>
          <div class="footerbg">
            <div class="footerleft">
              <div class="footercontent alignleft"> <a class="linkpadding" href="products.html">Products</a>| <a class="linkpadding" href="services.html">Services</a>| <a class="linkpadding" href="about.html">About</a>| <a class="linkpadding" href="contact.html">Contact</a> </div>
            </div>
            <div class="footerright">
              <div class="footercontent alignright">

              </div>
            </div>
          </div>
        </div>
        <!-- /footer -->
      </div>
      <div class="footerbottom"><img src="images/spacer.gif" alt="" border="0" /></div>
    </div>


  </body>
</html>